import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import process from "process";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Obsidian Git 中文版 - Chinese Localized Version
源代码: https://github.com/lyl224459/obsidian-git-zh
原版项目: https://github.com/Vinzent03/obsidian-git
*/
`;

const prod = process.argv[2] === "production";

console.log(`\n🔨 构建模式: ${prod ? '生产环境 (Production)' : '开发环境 (Development)'}`);
console.log(`📦 目标文件: main.js`);
console.log(`🌐 i18n 支持: 中文/English\n`);

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "child_process",
        "fs",
        "path",
        "moment",
        "node:events",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    platform: "browser",
    minify: prod,
    charset: "utf8",
    legalComments: "none",
    define: {
        "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    },
    conditions: [prod ? "production" : "development"], // https://www.npmjs.com/package/esm-env
    plugins: [
        esbuildSvelte({
            compilerOptions: {
                css: "injected",
                dev: !prod,
            },
            filterWarnings: (warning) => {
                if (warning.code.startsWith("a11y-")) return false;
                return true;
            },
            preprocess: sveltePreprocess(),
        }),
    ],
    inject: ["polyfill_buffer.js"],
    outfile: prod ? "dist/main.js" : "main.js",
});

if (prod) {
    console.log('🚀 开始生产构建...\n');
    await context.rebuild();
    console.log('\n✅ 构建完成！');
    console.log('📄 输出文件: main.js');
    console.log('🎯 已启用: 代码压缩, Tree Shaking, i18n 支持\n');
    process.exit(0);
} else {
    console.log('👀 监听文件变化中...\n');
    await context.watch();
}
